const { DataTypes } = require('sequelize');
const { sequelize } = require('../database');

const Player = sequelize.define('Player', {
    discordId: { type: DataTypes.STRING, unique: true, allowNull: false },
    username: { type: DataTypes.STRING, allowNull: false },
    level: { type: DataTypes.INTEGER, defaultValue: 1 },
    exp: { type: DataTypes.INTEGER, defaultValue: 0 },
    expNeeded: { type: DataTypes.INTEGER, defaultValue: 100 },
    statPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
    power: { type: DataTypes.INTEGER, defaultValue: 10 },
    defense: { type: DataTypes.INTEGER, defaultValue: 10 },
    speed: { type: DataTypes.INTEGER, defaultValue: 10 },
    hp: { type: DataTypes.INTEGER, defaultValue: 100 },
    maxHp: { type: DataTypes.INTEGER, defaultValue: 100 },
    gold: { type: DataTypes.INTEGER, defaultValue: 100 },
    diamond: { type: DataTypes.INTEGER, defaultValue: 0 },
    hollowCoin: { type: DataTypes.INTEGER, defaultValue: 0 },
    race: { type: DataTypes.STRING, defaultValue: 'human' },
    raceEvolution: { type: DataTypes.INTEGER, defaultValue: 0 },
    raceForm: { type: DataTypes.STRING, defaultValue: null },
    raceData: { type: DataTypes.JSONB, defaultValue: {} },
    equippedWeapon: { type: DataTypes.JSONB, defaultValue: null },
    equippedArmor: { type: DataTypes.JSONB, defaultValue: {} },
    equippedAccessory: { type: DataTypes.JSONB, defaultValue: {} },
    rankedPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
    rankedTier: { type: DataTypes.STRING, defaultValue: 'unranked' },
    clanId: { type: DataTypes.INTEGER, defaultValue: null },
    petId: { type: DataTypes.INTEGER, defaultValue: null },
    dailyLastUsed: { type: DataTypes.DATE, defaultValue: null },
    weeklyLastUsed: { type: DataTypes.DATE, defaultValue: null },
    inBattle: { type: DataTypes.BOOLEAN, defaultValue: false },
    totalKills: { type: DataTypes.INTEGER, defaultValue: 0 },
    totalBossKills: { type: DataTypes.INTEGER, defaultValue: 0 },
    totalDamageDealt: { type: DataTypes.BIGINT, defaultValue: 0 },
    winStreak: { type: DataTypes.INTEGER, defaultValue: 0 },
    bestWinStreak: { type: DataTypes.INTEGER, defaultValue: 0 },
    pvpWins: { type: DataTypes.INTEGER, defaultValue: 0 },
    pvpLosses: { type: DataTypes.INTEGER, defaultValue: 0 },
    seasonPassXp: { type: DataTypes.INTEGER, defaultValue: 0 },
    seasonPassTier: { type: DataTypes.INTEGER, defaultValue: 0 },
    friends: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
    achievements: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
    title: { type: DataTypes.STRING, defaultValue: null },
    cosmetics: { type: DataTypes.JSONB, defaultValue: {} },
    region: { type: DataTypes.STRING, defaultValue: 'karakura' },
    passiveIncomeLast: { type: DataTypes.DATE, defaultValue: null },
});

module.exports = Player;
