const { DataTypes } = require('sequelize');
const { sequelize } = require('../database');

const Player = sequelize.define('Player', {
    discordId: { type: DataTypes.STRING, unique: true, allowNull: false },
    username: { type: DataTypes.STRING, defaultValue: 'Unknown' },
    level: { type: DataTypes.INTEGER, defaultValue: 1 },
    exp: { type: DataTypes.INTEGER, defaultValue: 0 },
    hp: { type: DataTypes.INTEGER, defaultValue: 100 },
    maxHp: { type: DataTypes.INTEGER, defaultValue: 100 },
    power: { type: DataTypes.INTEGER, defaultValue: 10 },
    defense: { type: DataTypes.INTEGER, defaultValue: 5 },
    speed: { type: DataTypes.INTEGER, defaultValue: 10 },
    gold: { type: DataTypes.INTEGER, defaultValue: 0 },
    diamond: { type: DataTypes.INTEGER, defaultValue: 0 },
    race: { type: DataTypes.STRING, defaultValue: null },
    raceEvolution: { type: DataTypes.INTEGER, defaultValue: 0 },
    raceData: { type: DataTypes.JSONB, defaultValue: {} },
    inBattle: { type: DataTypes.BOOLEAN, defaultValue: false },
    equippedWeapon: { type: DataTypes.JSONB, defaultValue: null },
    equippedArmor: { type: DataTypes.JSONB, defaultValue: {} },
    equippedAccessory: { type: DataTypes.JSONB, defaultValue: {} },
    totalKills: { type: DataTypes.INTEGER, defaultValue: 0 },
    bossKills: { type: DataTypes.INTEGER, defaultValue: 0 },
    totalDamageDealt: { type: DataTypes.BIGINT, defaultValue: 0 },
    pvpWins: { type: DataTypes.INTEGER, defaultValue: 0 },
    pvpLosses: { type: DataTypes.INTEGER, defaultValue: 0 },
    winStreak: { type: DataTypes.INTEGER, defaultValue: 0 },
    bestWinStreak: { type: DataTypes.INTEGER, defaultValue: 0 },
    rankedPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
    seasonPassExp: { type: DataTypes.INTEGER, defaultValue: 0 },
    achievements: { type: DataTypes.JSONB, defaultValue: [] },
    dungeonClears: { type: DataTypes.INTEGER, defaultValue: 0 },
    clanId: { type: DataTypes.INTEGER, defaultValue: null },
    dailyStreak: { type: DataTypes.INTEGER, defaultValue: 0 },
    lastDaily: { type: DataTypes.DATE, defaultValue: null },
    lastPassiveIncome: { type: DataTypes.DATE, defaultValue: null },
    title: { type: DataTypes.STRING, defaultValue: null },
    banner: { type: DataTypes.STRING, defaultValue: null },
    expNeeded: { type: DataTypes.INTEGER, defaultValue: 100 },
    statPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
    seasonPassXp: { type: DataTypes.INTEGER, defaultValue: 0 },
    seasonPassTier: { type: DataTypes.INTEGER, defaultValue: 0 },
    rankedTier: { type: DataTypes.STRING, defaultValue: 'unranked' },
    passiveIncomeLast: { type: DataTypes.DATE, defaultValue: null },
    friends: { type: DataTypes.JSONB, defaultValue: [] },
});

module.exports = Player;
